language: node_js

node_js:
  - '5.1.0'

addons:
  firefox: '40.0.2'

before_install:
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo apt-get update -y
  - sudo apt-get install libappindicator1 fonts-liberation
  - sudo dpkg -i google-chrome-*.deb
  - export CHROME_BIN=`which google-chrome`

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - $CI_ACTION

env:
  global:
    - TEST_SUITE=unit
  matrix:
    - CI_ACTION="npm run lint"
    - CI_ACTION="npm test"

